version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: SenhaForte123
      POSTGRES_DB: jpa
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
